AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template specifies a route table for a specified VPC.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Route Table Configuration
        Parameters:
          - VpcId
    ParameterLabels:
      VpcId:
        default: VPC ID
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    ConstraintDescription: >
      VPC ID is required.
    Description: >
      The ID of the VPC the route table is associated with.
    MinLength: 1
Resources:
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags: 
        - Key: "Name"
          Value: !Ref AWS::StackName
      VpcId: !Ref VpcId
Outputs:
  SubnetId:
    Value: !Ref RouteTable