AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template specifies a route with a NAT gateway target in a 
  route table within a VPC.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Route with NAT Gateway Target Configuration
        Parameters:
          - DestinationCidrBlock
          - NatGatewayId
          - RouteTableId
    ParameterLabels:
      DestinationCidrBlock:
        default: Destination IPv4 CIDR Block
      NatGatewayId:
        default: NAT Gateway ID
      RouteTableId:
        default: Route Table ID
Parameters:
  DestinationCidrBlock:
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 0.0.0.0/0
    Description: The IPv4 CIDR block used for the destination match.
  NatGatewayId:
    Type: String
    ConstraintDescription: >
      NAT Gateway ID is required.
    Description: >
      The ID of the NAT gateway attached to your VPC.
    MinLength: 1
  RouteTableId:
    Type: String
    ConstraintDescription: >
      Route Table ID is required.
    Description: >
      The ID of the route table.
    MinLength: 1
Resources:
  Route:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: !Ref DestinationCidrBlock
      NatGatewayId: !Ref NatGatewayId
      RouteTableId: !Ref RouteTableId
Outputs:
  RouteId:
    Value: !Ref Route
