AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template specifies a subnet for a VPC.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Subnet Configuration
        Parameters:
          - pAssignIpv6AddressOnCreation
          - pAvailabilityZone
          - pCidrBlock
          - pIpv6CidrBlock
          - pMapPublicIpOnLaunch
          - pNameTag
          - pVpcId
    ParameterLabels:
      pAssignIpv6AddressOnCreation:
        default: Assign IPv6 Address on Creation
      pAvailabilityZone:
        default: Availability Zone
      pCidrBlock:
        default: IPv4 CIDR Block
      pIpv6CidrBlock:
        default: IPv6 CIDR Block
      pMapPublicIpOnLaunch:
        default: Map Public IP on Launch
      pNameTag:
        default: Name Tag
      pVpcId:
        default: VPC ID
Parameters:
  pAssignIpv6AddressOnCreation:
    Type: String
    AllowedValues:
      - false
      - true
    Default: false
    Description: >
      Indicates whether a network interface created in this subnet 
      receives an IPv6 address. 
  pAvailabilityZone:
    Type: String
    Description: >
      The Availability Zone of the subnet.
  pCidrBlock:
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Description: The IPv4 CIDR block assigned to the subnet.
  pIpv6CidrBlock:
    Type: String
    Description: The IPv6 CIDR block assigned to the subnet.
  pMapPublicIpOnLaunch:
    Type: String
    AllowedValues:
      - false
      - true
    Default: false
    Description: >
      Indicates whether instances launched in this subnet receive a public IPv4 address. 
  pNameTag:
    Type: String
    Description: >
      A tag with a key of 'Name' and a value that you specify.
  pVpcId:
    Type: AWS::EC2::VPC::Id
    ConstraintDescription: >
      VPC ID is required.
    Description: >
      The ID of the VPC the subnet is in.
    MinLength: 1
Conditions:
  cAssignIpv6AddressOnCreation:  !Equals [ !Ref pAssignIpv6AddressOnCreation, true ]
Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AssignIpv6AddressOnCreation: 
        !If 
          - cAssignIpv6AddressOnCreation
          - !Ref pAssignIpv6AddressOnCreation
          - !Ref AWS::NoValue
      AvailabilityZone: !Ref pAvailabilityZone
      CidrBlock: !Ref pCidrBlock
      Ipv6CidrBlock: 
        !If 
          - cAssignIpv6AddressOnCreation
          - !Ref pIpv6CidrBlock
          - !Ref AWS::NoValue
      MapPublicIpOnLaunch: 
        !If 
          - cAssignIpv6AddressOnCreation
          - !Ref AWS::NoValue
          - !Ref pMapPublicIpOnLaunch
      Tags: 
        - Key: "Name"
          Value: !Ref pNameTag
      VpcId: !Ref pVpcId
Outputs:
  SubnetId:
    Value: !Ref Subnet