AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template specifies a VPC with the specified IPv4 CIDR block. The
  smallest VPC you can create uses a /28 netmask (16 IPv4 addresses), 
  and the largest uses a /16 netmask (65,536 IPv4 addresses).
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VPC Configuration
        Parameters:
          - CidrBlock
          - EnableDnsHostnames
          - EnableDnsSupport
          - InstanceTenancy
          - NameTag
    ParameterLabels:
      CidrBlock:
        default: IPv4 CIDR Block
      EnableDnsHostnames:
        default: Enable DNS Hostnames
      EnableDnsSupport:
        default: Enable DNS Support
      InstanceTenancy:
        default: Instance Tenancy
      NameTag:
        default: Name Tag
Conditions:
  HasNameTag:  !Not [ !Equals [ !Ref NameTag, "" ] ]
Parameters:
  CidrBlock:
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.0.0/16
    Description: The primary IPv4 CIDR block for the VPC.
  EnableDnsHostnames:
    Type: String
    AllowedValues:
      - false
      - true
    Default: false
    Description: >
      Indicates whether the instances launched in the VPC get DNS 
      hostnames.
  EnableDnsSupport:
    Type: String
    AllowedValues:
      - false
      - true
    Default: true
    Description: >
      Indicates whether the DNS resolution is supported for the VPC.
  InstanceTenancy:
    Type: String
    AllowedValues:
      - dedicated
      - default 
      - host
    Description: >
      The allowed tenancy of instances launched into the VPC.
    Default: default
  NameTag:
    Type: String
    Description: >
      A tag with a key of 'Name' and a value that you specify.
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref CidrBlock
      EnableDnsHostnames: !Ref EnableDnsHostnames
      EnableDnsSupport: !Ref EnableDnsSupport
      InstanceTenancy: !Ref InstanceTenancy
      Tags: 
        !If 
          - HasNameTag
          - Key: "Name"
            Value: !Ref NameTag
          - !Ref AWS::NoValue
Outputs:
  VpcId:
    Value: !Ref VPC