AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template specifies a VPC with the specified IPv4 CIDR block. The
  smallest VPC you can create uses a /28 netmask (16 IPv4 addresses), 
  and the largest uses a /16 netmask (65,536 IPv4 addresses).
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VPC Configuration
        Parameters:
          - pCidrBlock
          - pEnableDnsHostnames
          - pEnableDnsSupport
          - pInstanceTenancy
          - pNameTag
    ParameterLabels:
      pCidrBlock:
        default: IPv4 CIDR Block
      pEnableDnsHostnames:
        default: Enable DNS Hostnames
      pEnableDnsSupport:
        default: Enable DNS Support
      pInstanceTenancy:
        default: Instance Tenancy
      pNameTag:
        default: Name Tag
Parameters:
  pCidrBlock:
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.0.0/16
    Description: The primary IPv4 CIDR block for the VPC.
  pEnableDnsHostnames:
    Type: String
    AllowedValues:
      - false
      - true
    Default: false
    Description: >
      Indicates whether the instances launched in the VPC get DNS 
      hostnames.
  pEnableDnsSupport:
    Type: String
    AllowedValues:
      - false
      - true
    Default: true
    Description: >
      Indicates whether the DNS resolution is supported for the VPC.
  pInstanceTenancy:
    Type: String
    AllowedValues:
      - dedicated
      - default 
      - host
    Description: >
      The allowed tenancy of instances launched into the VPC.
    Default: default
  pNameTag:
    Type: String
    Description: >
      A tag with a key of 'Name' and a value that you specify.
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref pCidrBlock
      EnableDnsHostnames: !Ref pEnableDnsHostnames
      EnableDnsSupport: !Ref pEnableDnsSupport
      InstanceTenancy: !Ref pInstanceTenancy
      Tags: 
        - Key: "Name"
          Value: !Ref pNameTag
Outputs:
  VpcId:
    Value: !Ref VPC